name: Deploy Serverless function
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v2
      with:
        token: ${{ secrets.YC_TOKEN }}
        function_id:  ${{ secrets.YCF_CORE_ID }}
        runtime: 'python311'
        memory: '128'
        entrypoint: 'handler.handler'
        environment: FB_PRIVATE_KEY=${{ secrets.PRIVATE_KEY }},FB_PRIVATE_KEY_ID=${{ secrets.PRIVATE_KEY_ID }}
        source: '.'
        exclude: '.git,.github'